// 中文翻译
const zh_CN = {
    selectLanguage: "选择语言",
    aboutText1: "少女乐团派对辅助工具集 / Wasmdori",
    frontPage: "前端代码",
    subProject: "子项目",
    helpProject: "感谢下面这些第三方项目的帮助！！！",
    hintText1: "选择服务器和截图后，点击截图中左上方的卡片，即可在截图右边的表格中选择识别出的卡片",
    hintText2: "在表格中选择识别出的卡片后，点击“生成”按钮就可以在下方看到生成的 Bestdori 用户资料",
    hintText3: "(可以使用多张图片导入数据，只需在“选择截图”处选择下一张图片就可以导入了)",
    cardRecognize: "卡片识别",
    teamBuilder: "组队助手",
    selectServer: "选择服务器",
    selectCharacter: "选择加成角色",
    userProfile: "用户资料",
    selectParameter: "选择加成技能",
    selectProperty: "选择加成属性",
    selectScreenshot: "选择截图",
    waitRecognize: "等待识别",
    cardImage: "图片",
    id: "Id",
    cardName: "卡片名字",
    character: "角色",
    selected: "选中",
    nextPage: "下一页",
    prevPage: "上一页",
    selectAll: "全选",
    generate: "生成",
    showImage: "显示图片",
    hideImage: "隐藏图片",
    performance: "演出",
    technique: "技巧",
    visual: "形象",
    propBonus: "属性加成大小",
    characterBonus: "角色加成大小",
    allFitBonus: "所有匹配时加成大小",
    selectProfile: "选择用户资料",
    profile: "用户资料",
    profileName: "资料名字",
    profileServer: "资料服务器",
    importProfileData: "导入资料数据",
    setPrimaryData: "设置为首选资料",
    createNewProfile: "创建新资料",
    deleteProfile: "删除资料"
};

// English translation
const en_US = {
    selectLanguage: "Select language",
    aboutText1: "Bandori band girl party assist tools / Wasmdori",
    frontPage: "Front-end project",
    subProject: "Sub project",
    helpProject: "Thank you, the following third-party projects!!!",
    hintText1: "After selected server and screenshot, click the card on the left-top in the screenshot, you will see the recognized card in the left table",
    hintText2: "After selected the recognized card in the table, click \"Generate\" button to generate the user profile that can be used by Bestdori",
    hintText3: "(You can use multiple screenshot to generate user profile, just use \"Select screenshot\" to add next screenshot)",
    cardRecognize: "Card Recognize",
    teamBuilder: "Team Builder",
    selectServer: "Select server",
    selectCharacter: "Select bonus Character",
    userProfile: "User profile",
    selectParameter: "Select bonus parameter",
    selectProperty: "Select bonus property",
    selectScreenshot: "Select screenshot",
    waitRecognize: "Waiting for card recognition",
    cardImage: "Image",
    id: "Id",
    cardName: "Card name",
    character: "Character",
    selected: "Selected",
    nextPage: "Next page",
    prevPage: "Prev page",
    selectAll: "Select all",
    generate: "Generate",
    showImage: "Show image",
    hideImage: "Hide image",
    performance: "Performance",
    technique: "Technique",
    visual: "Visual",
    propBonus: "Prop bonus",
    characterBonus: "Character bonus",
    allFitBonus: "All fit bonus",
    profile: "User Profile",
    selectProfile: "Select profile",
    profileName: "Profile name",
    profileServer: "Profile server",
    importProfileData: "Import profile",
    setPrimaryData: "Set as primary profile",
    createNewProfile: "Create new profile",
    deleteProfile: "Delete profile"
}

// TODO: More translation and language
const translates = [en_US, en_US, zh_CN, zh_CN];

export { translates }